### ISSUE TITLE
add new maintainer

### ISSUE THREAD

**Issue by davefeilseifer** [pr2-gbp/pr2_robot-release#1]
@davefeilseifer is willing to take over maintenance of this package.

**Comment by tfoote** [comment]
@TheDash  @wjwwood Could you help here I don't have access.

**Comment by wjwwood** [comment]
Do you need access to https://github.com/pr2/pr2_robot too?

**Comment by tfoote** [comment]
Thanks @wjwwood I already granted that. https://github.com/PR2/pr2_robot/issues/253

**Comment by wjwwood** [comment]
Ok, I've invited @davefeilseifer. So this can probably be closed, and reopened if something went wrong.
